component_version: 1.0.0

queues:
  -
    name: queue1
    visibility_timeout: 60
    delay_seconds: 20
    maximum_message_size: 1024
    message_retention_period: 300
    receive_message_wait_time_seconds: 120
  -
    name: queue2
