component_version: 1.0.0

queues:
  -
    name: queue1
    visibility_timeout: 60
    delay_seconds: 20
    maximum_message_size: 1024
    message_retention_period: 300
    receive_message_wait_time_seconds: 20
    # kms_master_key: alias/aws/sqs
  -
    name: queue2
    # kms_master_key: alias/aws/sqs
    # kms_data_key_reuse_seconds: 3600
